workflow:
  rules:
    # Run the generic CI on merge requests only
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - check
  - build

issue-check:
  stage: check
  interruptible: true
  needs: []
  variables:
    GIT_STRATEGY: none
  services:
    - image:pe-base
  script:
    - require_issue

build_and_test:
  stage: build
  interruptible: true
  services:
    - image:pe-base
    - cpu:8
    - mem:16
  script:
    - generic_anod_ci
    - . /tmp/ci_env.sh
    - anod test gnatformat $ACI_TRACK_QUALIFIER
    - testsuite_reports
  artifacts:
    reports:
      junit: xunit-*.xml
