repos:
  - repo: local
    hooks:
      - id: gnatformat
        name: Run gnatformat
        entry: gnatformat_edge
        verbose: true
        language: system
        files: ".*\\.ad(b|s)"
        exclude: "testsuite/tests/.*"
        args: ["-P", "gnat/gnatformat_driver.gpr"]
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        types_or: [file]
        files: \.(py)$
